# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

[wallpaper]
backend = "mpvpaper"
custom_paths = ["/home/hulff/Imagens/wallpapers"]
filetypes = [ "mp4", "mkv" ]

